// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/icc/icc.proto

package icc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreSignObjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ObjectID - generally, it is equal to filename
	//
	// For better robustness, ICC will generate an unique ID to identify the object.
	// Using ForceObjectID and specifying ObjectID to override this behavior and
	// defined the objectID by yourself.
	ForceObjectID *bool   `protobuf:"varint,3,opt,name=ForceObjectID,proto3,oneof" json:"ForceObjectID,omitempty"`
	ObjectID      *string `protobuf:"bytes,1,opt,name=ObjectID,proto3,oneof" json:"ObjectID,omitempty"`
	// ExpireSeconds - specifies how long the object will expire
	ExpireSeconds uint32 `protobuf:"varint,2,opt,name=ExpireSeconds,proto3" json:"ExpireSeconds,omitempty"`
}

func (x *PreSignObjectRequest) Reset() {
	*x = PreSignObjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_icc_icc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreSignObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreSignObjectRequest) ProtoMessage() {}

func (x *PreSignObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_icc_icc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreSignObjectRequest.ProtoReflect.Descriptor instead.
func (*PreSignObjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_icc_icc_proto_rawDescGZIP(), []int{0}
}

func (x *PreSignObjectRequest) GetForceObjectID() bool {
	if x != nil && x.ForceObjectID != nil {
		return *x.ForceObjectID
	}
	return false
}

func (x *PreSignObjectRequest) GetObjectID() string {
	if x != nil && x.ObjectID != nil {
		return *x.ObjectID
	}
	return ""
}

func (x *PreSignObjectRequest) GetExpireSeconds() uint32 {
	if x != nil {
		return x.ExpireSeconds
	}
	return 0
}

type PreSignObjectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Status - more specifically, the StatusCode to identity the process status
	// generally, Status == 0 means request successes.
	Status  int32        `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message string       `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data    *PreSignData `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *PreSignObjectResponse) Reset() {
	*x = PreSignObjectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_icc_icc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreSignObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreSignObjectResponse) ProtoMessage() {}

func (x *PreSignObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_icc_icc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreSignObjectResponse.ProtoReflect.Descriptor instead.
func (*PreSignObjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_icc_icc_proto_rawDescGZIP(), []int{1}
}

func (x *PreSignObjectResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PreSignObjectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PreSignObjectResponse) GetData() *PreSignData {
	if x != nil {
		return x.Data
	}
	return nil
}

type PreSignData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ObjectID - the unique ID of the object
	// If ForceObjectID is false, the ObjectID is the unique ID generate by ICC
	// else, the objectID is the ID defined in PreSignObjectRequest
	ObjectID string `protobuf:"bytes,1,opt,name=ObjectID,proto3" json:"ObjectID,omitempty"`
}

func (x *PreSignData) Reset() {
	*x = PreSignData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_icc_icc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreSignData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreSignData) ProtoMessage() {}

func (x *PreSignData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_icc_icc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreSignData.ProtoReflect.Descriptor instead.
func (*PreSignData) Descriptor() ([]byte, []int) {
	return file_proto_icc_icc_proto_rawDescGZIP(), []int{2}
}

func (x *PreSignData) GetObjectID() string {
	if x != nil {
		return x.ObjectID
	}
	return ""
}

type UpsertImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectID string `protobuf:"bytes,1,opt,name=ObjectID,proto3" json:"ObjectID,omitempty"`
	Tags     []*Tag `protobuf:"bytes,2,rep,name=Tags,proto3" json:"Tags,omitempty"`
	// ExternalID - optional ID to identity an image.
	// Usually, it is no need to set it unless user wants.
	ExternalID *string `protobuf:"bytes,3,opt,name=ExternalID,proto3,oneof" json:"ExternalID,omitempty"`
}

func (x *UpsertImageRequest) Reset() {
	*x = UpsertImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_icc_icc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertImageRequest) ProtoMessage() {}

func (x *UpsertImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_icc_icc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertImageRequest.ProtoReflect.Descriptor instead.
func (*UpsertImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_icc_icc_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertImageRequest) GetObjectID() string {
	if x != nil {
		return x.ObjectID
	}
	return ""
}

func (x *UpsertImageRequest) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpsertImageRequest) GetExternalID() string {
	if x != nil && x.ExternalID != nil {
		return *x.ExternalID
	}
	return ""
}

type Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name - typically, using English as its standard name
	Name  string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Alias []string `protobuf:"bytes,2,rep,name=Alias,proto3" json:"Alias,omitempty"`
}

func (x *Tag) Reset() {
	*x = Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_icc_icc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_icc_icc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_proto_icc_icc_proto_rawDescGZIP(), []int{4}
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetAlias() []string {
	if x != nil {
		return x.Alias
	}
	return nil
}

type UpsertImageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Status - more specifically, the StatusCode to identity the process status
	// generally, Status == 0 means request successes.
	Status  int32  `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *UpsertImageResponse) Reset() {
	*x = UpsertImageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_icc_icc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertImageResponse) ProtoMessage() {}

func (x *UpsertImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_icc_icc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertImageResponse.ProtoReflect.Descriptor instead.
func (*UpsertImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_icc_icc_proto_rawDescGZIP(), []int{5}
}

func (x *UpsertImageResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpsertImageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_icc_icc_proto protoreflect.FileDescriptor

var file_proto_icc_icc_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x63, 0x63, 0x2f, 0x69, 0x63, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x69, 0x63, 0x63, 0x22, 0xa7, 0x01, 0x0a, 0x14, 0x50,
	0x72, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x0d, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x0d, 0x46, 0x6f,
	0x72, 0x63, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x88, 0x01, 0x01, 0x12, 0x1f,
	0x0a, 0x08, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x08, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x88, 0x01, 0x01, 0x12,
	0x24, 0x0a, 0x0d, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x53, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x73, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x49, 0x44, 0x22, 0x6f, 0x0a, 0x15, 0x50, 0x72, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x24, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x69, 0x63, 0x63, 0x2e, 0x50, 0x72, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x29, 0x0a, 0x0b, 0x50, 0x72, 0x65, 0x53, 0x69, 0x67, 0x6e,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44,
	0x22, 0x82, 0x01, 0x0a, 0x12, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x04, 0x54, 0x61, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x69, 0x63, 0x63, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x04, 0x54, 0x61, 0x67,
	0x73, 0x12, 0x23, 0x0a, 0x0a, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x44, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x49, 0x44, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x45, 0x78, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x49, 0x44, 0x22, 0x2f, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x22, 0x47, 0x0a, 0x13, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32,
	0xeb, 0x01, 0x0a, 0x03, 0x49, 0x43, 0x43, 0x12, 0x4b, 0x0a, 0x12, 0x49, 0x73, 0x73, 0x75, 0x65,
	0x50, 0x72, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x19, 0x2e,
	0x69, 0x63, 0x63, 0x2e, 0x50, 0x72, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x69, 0x63, 0x63, 0x2e, 0x50,
	0x72, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x14, 0x49, 0x73, 0x73, 0x75, 0x65, 0x50, 0x72, 0x65,
	0x53, 0x69, 0x67, 0x6e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x19, 0x2e, 0x69,
	0x63, 0x63, 0x2e, 0x50, 0x72, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x69, 0x63, 0x63, 0x2e, 0x50, 0x72,
	0x65, 0x53, 0x69, 0x67, 0x6e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x13, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x57, 0x69, 0x74, 0x68, 0x54, 0x61, 0x67, 0x73, 0x12, 0x17, 0x2e, 0x69, 0x63, 0x63,
	0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x69, 0x63, 0x63, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2c, 0x5a,
	0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x79, 0x6c, 0x6f,
	0x6e, 0x78, 0x2f, 0x69, 0x63, 0x63, 0x2d, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x69, 0x63, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_icc_icc_proto_rawDescOnce sync.Once
	file_proto_icc_icc_proto_rawDescData = file_proto_icc_icc_proto_rawDesc
)

func file_proto_icc_icc_proto_rawDescGZIP() []byte {
	file_proto_icc_icc_proto_rawDescOnce.Do(func() {
		file_proto_icc_icc_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_icc_icc_proto_rawDescData)
	})
	return file_proto_icc_icc_proto_rawDescData
}

var file_proto_icc_icc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_icc_icc_proto_goTypes = []interface{}{
	(*PreSignObjectRequest)(nil),  // 0: icc.PreSignObjectRequest
	(*PreSignObjectResponse)(nil), // 1: icc.PreSignObjectResponse
	(*PreSignData)(nil),           // 2: icc.PreSignData
	(*UpsertImageRequest)(nil),    // 3: icc.UpsertImageRequest
	(*Tag)(nil),                   // 4: icc.Tag
	(*UpsertImageResponse)(nil),   // 5: icc.UpsertImageResponse
}
var file_proto_icc_icc_proto_depIdxs = []int32{
	2, // 0: icc.PreSignObjectResponse.Data:type_name -> icc.PreSignData
	4, // 1: icc.UpsertImageRequest.Tags:type_name -> icc.Tag
	0, // 2: icc.ICC.IssuePreSignUpload:input_type -> icc.PreSignObjectRequest
	0, // 3: icc.ICC.IssuePreSignDownload:input_type -> icc.PreSignObjectRequest
	3, // 4: icc.ICC.UpsertImageWithTags:input_type -> icc.UpsertImageRequest
	1, // 5: icc.ICC.IssuePreSignUpload:output_type -> icc.PreSignObjectResponse
	1, // 6: icc.ICC.IssuePreSignDownload:output_type -> icc.PreSignObjectResponse
	5, // 7: icc.ICC.UpsertImageWithTags:output_type -> icc.UpsertImageResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_icc_icc_proto_init() }
func file_proto_icc_icc_proto_init() {
	if File_proto_icc_icc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_icc_icc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreSignObjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_icc_icc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreSignObjectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_icc_icc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreSignData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_icc_icc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_icc_icc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_icc_icc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertImageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_icc_icc_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_proto_icc_icc_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_icc_icc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_icc_icc_proto_goTypes,
		DependencyIndexes: file_proto_icc_icc_proto_depIdxs,
		MessageInfos:      file_proto_icc_icc_proto_msgTypes,
	}.Build()
	File_proto_icc_icc_proto = out.File
	file_proto_icc_icc_proto_rawDesc = nil
	file_proto_icc_icc_proto_goTypes = nil
	file_proto_icc_icc_proto_depIdxs = nil
}
