// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package icc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ICCClient is the client API for ICC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ICCClient interface {
	// Issue Pre-Sign request
	// For Pre-Sign upload request, the client should send HTTP PUT request
	// For Pre-Sign download request, the client should send HTTP GET request
	IssuePreSignUpload(ctx context.Context, in *PreSignObjectRequest, opts ...grpc.CallOption) (*PreSignObjectResponse, error)
	IssuePreSignDownload(ctx context.Context, in *PreSignObjectRequest, opts ...grpc.CallOption) (*PreSignObjectResponse, error)
	UpsertImageWithTags(ctx context.Context, in *UpsertImageRequest, opts ...grpc.CallOption) (*UpsertImageResponse, error)
}

type iCCClient struct {
	cc grpc.ClientConnInterface
}

func NewICCClient(cc grpc.ClientConnInterface) ICCClient {
	return &iCCClient{cc}
}

func (c *iCCClient) IssuePreSignUpload(ctx context.Context, in *PreSignObjectRequest, opts ...grpc.CallOption) (*PreSignObjectResponse, error) {
	out := new(PreSignObjectResponse)
	err := c.cc.Invoke(ctx, "/icc.ICC/IssuePreSignUpload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iCCClient) IssuePreSignDownload(ctx context.Context, in *PreSignObjectRequest, opts ...grpc.CallOption) (*PreSignObjectResponse, error) {
	out := new(PreSignObjectResponse)
	err := c.cc.Invoke(ctx, "/icc.ICC/IssuePreSignDownload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iCCClient) UpsertImageWithTags(ctx context.Context, in *UpsertImageRequest, opts ...grpc.CallOption) (*UpsertImageResponse, error) {
	out := new(UpsertImageResponse)
	err := c.cc.Invoke(ctx, "/icc.ICC/UpsertImageWithTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ICCServer is the server API for ICC service.
// All implementations must embed UnimplementedICCServer
// for forward compatibility
type ICCServer interface {
	// Issue Pre-Sign request
	// For Pre-Sign upload request, the client should send HTTP PUT request
	// For Pre-Sign download request, the client should send HTTP GET request
	IssuePreSignUpload(context.Context, *PreSignObjectRequest) (*PreSignObjectResponse, error)
	IssuePreSignDownload(context.Context, *PreSignObjectRequest) (*PreSignObjectResponse, error)
	UpsertImageWithTags(context.Context, *UpsertImageRequest) (*UpsertImageResponse, error)
	mustEmbedUnimplementedICCServer()
}

// UnimplementedICCServer must be embedded to have forward compatible implementations.
type UnimplementedICCServer struct {
}

func (UnimplementedICCServer) IssuePreSignUpload(context.Context, *PreSignObjectRequest) (*PreSignObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssuePreSignUpload not implemented")
}
func (UnimplementedICCServer) IssuePreSignDownload(context.Context, *PreSignObjectRequest) (*PreSignObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssuePreSignDownload not implemented")
}
func (UnimplementedICCServer) UpsertImageWithTags(context.Context, *UpsertImageRequest) (*UpsertImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertImageWithTags not implemented")
}
func (UnimplementedICCServer) mustEmbedUnimplementedICCServer() {}

// UnsafeICCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ICCServer will
// result in compilation errors.
type UnsafeICCServer interface {
	mustEmbedUnimplementedICCServer()
}

func RegisterICCServer(s grpc.ServiceRegistrar, srv ICCServer) {
	s.RegisterService(&ICC_ServiceDesc, srv)
}

func _ICC_IssuePreSignUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreSignObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ICCServer).IssuePreSignUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/icc.ICC/IssuePreSignUpload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ICCServer).IssuePreSignUpload(ctx, req.(*PreSignObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ICC_IssuePreSignDownload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreSignObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ICCServer).IssuePreSignDownload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/icc.ICC/IssuePreSignDownload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ICCServer).IssuePreSignDownload(ctx, req.(*PreSignObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ICC_UpsertImageWithTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ICCServer).UpsertImageWithTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/icc.ICC/UpsertImageWithTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ICCServer).UpsertImageWithTags(ctx, req.(*UpsertImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ICC_ServiceDesc is the grpc.ServiceDesc for ICC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ICC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "icc.ICC",
	HandlerType: (*ICCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssuePreSignUpload",
			Handler:    _ICC_IssuePreSignUpload_Handler,
		},
		{
			MethodName: "IssuePreSignDownload",
			Handler:    _ICC_IssuePreSignDownload_Handler,
		},
		{
			MethodName: "UpsertImageWithTags",
			Handler:    _ICC_UpsertImageWithTags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/icc/icc.proto",
}
