/*
	Code generated by config2go(https://github.com/xylonx/config2go)
	DON EDIT!
*/
package config

type Setting struct {
	Application struct {
		AdminToken              string   `mapstructure:"admin_token" json:"admin_token" yaml:"admin_token" `
		GrpcHost                string   `mapstructure:"grpc_host" json:"grpc_host" yaml:"grpc_host" `
		GrpcPort                int64    `mapstructure:"grpc_port" json:"grpc_port" yaml:"grpc_port" `
		HttpAllowOrigins        []string `mapstructure:"http_allow_origins" json:"http_allow_origins" yaml:"http_allow_origins" `
		HttpHost                string   `mapstructure:"http_host" json:"http_host" yaml:"http_host" `
		HttpPort                int64    `mapstructure:"http_port" json:"http_port" yaml:"http_port" `
		HttpReadTimeoutSeconds  int64    `mapstructure:"http_read_timeout_seconds" json:"http_read_timeout_seconds" yaml:"http_read_timeout_seconds" `
		HttpWriteTimeoutSeconds int64    `mapstructure:"http_write_timeout_seconds" json:"http_write_timeout_seconds" yaml:"http_write_timeout_seconds" `
	} `mapstructure:"application" json:"application" yaml:"application" `
	Database struct {
		Postgres struct {
			Dsn            string `mapstructure:"dsn" json:"dsn" yaml:"dsn" `
			MaxIdleConn    int64  `mapstructure:"max_idle_conn" json:"max_idle_conn" yaml:"max_idle_conn" `
			MaxLifeSeconds int64  `mapstructure:"max_life_seconds" json:"max_life_seconds" yaml:"max_life_seconds" `
			MaxOpenConn    int64  `mapstructure:"max_open_conn" json:"max_open_conn" yaml:"max_open_conn" `
		} `mapstructure:"postgres" json:"postgres" yaml:"postgres" `
	} `mapstructure:"database" json:"database" yaml:"database" `
	Storage struct {
		CdnHost string `mapstructure:"cdn_host" json:"cdn_host" yaml:"cdn_host" `
		S3      struct {
			AccessId     string `mapstructure:"access_id" json:"access_id" yaml:"access_id" `
			AccessSecret string `mapstructure:"access_secret" json:"access_secret" yaml:"access_secret" `
			Bucket       string `mapstructure:"bucket" json:"bucket" yaml:"bucket" `
			Endpoint     string `mapstructure:"endpoint" json:"endpoint" yaml:"endpoint" `
			Region       string `mapstructure:"region" json:"region" yaml:"region" `
		} `mapstructure:"s3" json:"s3" yaml:"s3" `
		SignUploadSeconds int64 `mapstructure:"sign_upload_seconds" json:"sign_upload_seconds" yaml:"sign_upload_seconds" `
	} `mapstructure:"storage" json:"storage" yaml:"storage" `
}
